Fs_ds = 5;
GauSigma_second = 1;
Spacing_second = 1;

%% Close Exam, Mount, Escape, Dig, Feed, LBgroom, UBgroom
varargin_GLMGeneral = {'UseGaussian', true, 'GauSigma', Fs_ds * GauSigma_second,...
    'GauSpacing', Fs_ds * Spacing_second, 'useRampUp', false,...
    'useRampDown', false, 'useCopy', false, 'useStep', false};

BASIS_CloEx = GLMbasisphotom(datastruct_pp.CloseExam, varargin_GLMGeneral);
BASIS_Mount = GLMbasisphotom(datastruct_pp.Mount, varargin_GLMGeneral);
% BASIS_Escape = GLMbasisphotom(datastruct_pp.Escape, varargin_General);
BASIS_Dig = GLMbasisphotom(datastruct_pp.Dig, varargin_GLMGeneral);
BASIS_Feed = GLMbasisphotom(datastruct_pp.Feed, varargin_GLMGeneral);
BASIS_LBgroom = GLMbasisphotom(datastruct_pp.LBgroom, varargin_GLMGeneral);
BASIS_UBgroom = GLMbasisphotom(datastruct_pp.UBgroom, varargin_GLMGeneral);

%% Intromission
varargin_GLMintro = {'UseGaussian', true, 'GauSigma', Fs_ds * GauSigma_second,...
    'GauSpacing', Fs_ds * Spacing_second, 'useRampUp', true,...
    'RampUpJitterSpacing', Fs_ds * Spacing_second, 'RampUpJitterN', 3, ...
    'useRampDown', false, 'RampDownJitterSpacing', Fs_ds * Spacing_second,...
    'RampDownJitterN', 3, 'useCopy', false, 'CopyJitterSpacing',...
    Fs_ds * Spacing_second, 'CopyJitterN', 3, 'useStep', false};

BASIS_intro = GLMbasisphotom(datastruct_pp.Introm, varargin_GLMintro);

%% Transfer
varargin_GLMtransfer = {'UseGaussian', true, 'GauSigma', Fs_ds * GauSigma_second,...
    'GauSpacing', Fs_ds * Spacing_second, 'useRampUp', true,...
    'RampUpJitterSpacing', Fs_ds * Spacing_second, 'RampUpJitterN', 3, ...
    'useRampDown', true, 'RampDownJitterSpacing', Fs_ds * Spacing_second,...
    'RampDownJitterN', 3, 'useCopy', false, 'CopyJitterSpacing',...
    Fs_ds * Spacing_second, 'CopyJitterN', 3, 'useStep', true,...
    'EventToStep', 'last', 'StepWhen', 'offset', 'StepJitterSpacing',...
    Fs_ds * Spacing_second, 'StepJitterN', 3};

BASIS_transfer = GLMbasisphotom(datastruct_pp.Introm, varargin_GLMtransfer);

%% States
varargin_State_IntroTransfer = {'DynamicOnOffset', 'onset',...
    'WhichStaticEvent', 'last', 'StaticOnOffset', 'offset',...
    'useDynBeforeSta', true, 'useDynAfterSta', true};
State_IntroTransfer = GLMmakestate(datastruct_pp.Introm,...
    datastruct_pp.Transfer, varargin_State_IntroTransfer);


%%
BASIS_total = [BASIS_CloEx, BASIS_Mount, BASIS_Dig, ...
    BASIS_Feed, BASIS_LBgroom,BASIS_UBgroom,BASIS_transfer, ...
    BASIS_intro, State_IntroTransfer];
test = glmfit(BASIS_total, datastruct_pp.photometry, 'normal');
plot([datastruct_pp.photometry, BASIS_total * test(2:end) + test(1)])