%% GLM basis functions
% User variables 
GauSigma = 1; % in seconds
SpacingBasis = 1; % in seconds

% General inputs
varargin_GLMGeneral = {'Fs', [], 'UseGaussian', true, 'GauSigma', GauSigma,...
    'GauSpacing', SpacingBasis, 'nGauBefore', 3, 'nGauAfter', 3, 'useRampUp', false,...
    'useRampDown', false, 'useCopy', false, 'useStep', false};

% Introm inputs
varargin_GLMintro = {'Fs', [], 'UseGaussian', true, 'GauSigma', GauSigma,...
    'GauSpacing', SpacingBasis, 'nGauBefore', 3, 'nGauAfter', 3, 'useRampUp', true,...
    'RampUpJitterSpacing', SpacingBasis, 'RampUpJitterN', 3, ...
    'useRampDown', false, 'RampDownJitterSpacing', SpacingBasis,...
    'RampDownJitterN', 3, 'useCopy', false, 'CopyJitterSpacing',...
    SpacingBasis, 'CopyJitterN', 5, 'useStep', false};

% Transfer inputs
varargin_GLMtransfer = {'Fs', [], 'UseGaussian', true, 'GauSigma', GauSigma,...
    'GauSpacing', SpacingBasis, 'nGauBefore', 3, 'nGauAfter', 3, 'useRampUp', true,...
    'RampUpJitterSpacing', SpacingBasis, 'RampUpJitterN', 3, ...
    'useRampDown', true, 'RampDownJitterSpacing', SpacingBasis,...
    'RampDownJitterN', 3, 'useCopy', false, 'CopyJitterSpacing',...
    SpacingBasis, 'CopyJitterN', 3, 'useStep', true,...
    'EventToStep', 'last', 'StepWhen', 'offset', 'StepJitterSpacing',...
    SpacingBasis, 'StepJitterN', 3};

% All simple basis function inputs
varargin_simplebasis = {'varargin_GLMGeneral', varargin_GLMGeneral;...
    'varargin_GLMintro', varargin_GLMintro;...
    'varargin_GLMtransfer', varargin_GLMtransfer};

% IntroTransfer state input
varargin_State_IntroTransfer = {'Name', 'IntroTransfer', 'DynamicOnOffset', 'onset',...
    'WhichStaticEvent', 'last', 'StaticOnOffset', 'offset',...
    'useDynBeforeSta', true, 'useDynAfterSta', true, 'useRampUp', true,...
    'useRampDown', true, 'useCopy', true};

% Formula for generating simple basis functions
basis_formula = {'FemInvest', ''; 'CloseExam', 'varargin_GLMGeneral'; ...
    'Mount', 'varargin_GLMGeneral'; 'Introm', 'varargin_GLMintro'; 'Transfer',...
    'varargin_GLMtransfer'; 'Escape', 'varargin_GLMGeneral'; 'Dig',...
    'varargin_GLMGeneral'; 'Feed', 'varargin_GLMGeneral'; 'LBgroom',...
    'varargin_GLMGeneral'; 'UBgroom', 'varargin_GLMGeneral';...
    'varargins', varargin_simplebasis};

% Formula for generating state basis functions
state_formula = {'Introm', 'Transfer', varargin_State_IntroTransfer};

% Make basis functions
basisstruct = GLMbasisbatch(datastruct_pp, 'photometry', basis_formula, state_formula);

%% Align basis functions
% Formula for aligning basis functions
sync_formula = {'FemInvest', ''; 'CloseExam', 'alignfront'; 'Mount',...
    'alignfront'; 'Introm', 'alignback'; 'Transfer', 'alignfront';...
    'Escape', 'alignfront'; 'Dig', 'alignfront'; 'Feed', 'alignfront';...
    'LBgroom', 'alignfront'; 'UBgroom', 'alignfront'; 'IntroTransfer',...
    'alignback'};

% Align basis functions
basisstruct_sync = GLMbasissync(basisstruct, sync_formula);

%% Split up the dataset in to a training set and a testing set
% Trainig set matrix
tr_mat = [1 1 0 1 0; 0 1 1 1 1; 1 1 0 1 1; 1 1 1 0 1];

% Testing set matrix
te_mat = 1 - tr_mat;

varargin_split = {'train_mat', tr_mat, 'test_mat', te_mat};
[basisstruct_train, basisstruct_test] = GLMbasissplit(basisstruct_sync, varargin_split);

%% GLM fitting and testing
% Regularizaiton method;
regmet = 'lasso';

% GLM fitting parameters
varargin_GLMfit = {'MODE', 'fit', 'PlotOrNot', true, 'SetsToUse', [],...
    'Regularization', regmet, 'Lambda', 0.1, 'Alpha', 0.01,...
    'Standardize', false};

% GLM fitting
disp('=============================================')
fprintf('GLM fitting...')
tic;
[Model_coef, ~, ~, ~] =...
    GLMdophotom(basisstruct_train, varargin_GLMfit);
fprintf('Done. ');
toc
% disp(['Deviance explained (fitting): ', num2str(Deviance_explained.all)]);

% GLM testing parameters
varargin_GLMtest = {'MODE', 'test', 'PlotOrNot', true, 'SetsToUse', [],...
    'Coef', Model_coef, 'Regularization', regmet, 'detailedDevex', true};

% GLM testing
fprintf('GLM testing...')
tic;
[~, Deviance_explained, ~, ~] =...
    GLMdophotom(basisstruct_test, varargin_GLMtest);
fprintf('Done. ');
toc
disp(['Deviance explained (testing): ', num2str(Deviance_explained.all)]);

% GLM visualize parameters
varargin_GLMvis = {'MODE', 'visualize', 'PlotOrNot', true, 'SetsToUse', 2,...
    'Coef', Model_coef, 'Regularization', regmet};
[~, ~, ~, ~] =...
    GLMdophotom(basisstruct_sync, varargin_GLMvis);