%% Initialize
clear

% Default path
defaultpath = '\\anastasia\data\photometry';

% Which data files to look at {mouse, date, run}
inputloadingcell_MPOAdLightNaive = {'SZ268', 200109, 1; 'SZ270', 200109, 1;...
    'SZ272', 200109, 1; 'SZ273', 200109, 1; 'SZ274', 200109, 1; 'SZ268', 200110, 1;...
    'SZ270', 200110, 1; 'SZ272', 200110, 1; 'SZ273', 200110, 1; 'SZ274', 200110, 1;...
    'SZ268', 200115, 1; 'SZ270', 200115, 1; 'SZ272', 200115, 1; 'SZ273', 200115, 1;...
    'SZ274', 200115, 1; 'SZ268', 200117, 1; 'SZ270', 200117, 1; 'SZ272', 200117, 1;...
    'SZ273', 200117, 1; 'SZ274', 200117, 1; 'SZ268', 200123, 1; 'SZ270', 200123, 1;...
    'SZ272', 200123, 1; 'SZ273', 200123, 1; 'SZ274', 200123, 1;}; 
tcpCheck(inputloadingcell_MPOAdLightNaive, 'twocolor', false, 'headfixed', true);

inputloadingcell_MPOAdLightSatiated = {'SZ268', 200130, 1; 'SZ270', 200130, 1;...
    'SZ268', 200131, 1; 'SZ270', 200131, 1};
tcpCheck(inputloadingcell_MPOAdLightSatiated, 'twocolor', false, 'headfixed', true);

inputloadingcell_MPOAdLightShamSatiated = {'SZ272', 200131, 1; 'SZ273', 200131, 1;...
    'SZ274', 200131, 1;};
tcpCheck(inputloadingcell_MPOAdLightShamSatiated, 'twocolor', false, 'headfixed', true);
%% Fix stuff
%{
tcpFixTrigger(inputloadingcell_MPOAdLightShamSatiated, 'defaultpath', defaultpath,...
    'flatten_unfiltered', true, 'add_opto', true, 'checkfield', '', 'reduce_opto', true,...
    'add_running', true);
%}

%% Get Zs
%
tcpZ([inputloadingcell_MPOAdLightNaive;inputloadingcell_MPOAdLightSatiated;...
    inputloadingcell_MPOAdLightShamSatiated], 'flattenbeforez', true,...
    'defaultpath', defaultpath);
%}

%% Low-pass filter
% Get a better filter
d = fdesign.lowpass('Fp,Fst,Ap,Ast',7,9,0.5,40, 50);
Hd = design(d,'equiripple');

%% Make experimental data struct
% Experimental group
[datastruct_MPOAdLightNaive, n_series_MPOAdLightNaive] =...
    mkoptostruct(inputloadingcell_MPOAdLightNaive, 'defaultpath', defaultpath,...
    'externalsigma', [], 'zero_baseline', true, 'zero_baseline_per_session', true,...
    'linearleveling', false, 'useunfiltered', true, 'refilter', Hd, 'checkoptopulses', false,...
    'useinternalsigma', true);

%% View data struct experimental
% 
sets = [1 2 3 4 5 7 8 10 11 12 13 14 15 17 18 20 21 23 24];
varargin_viewopto = {'datasets', sets, 'flip_signal', false, 'yrange', [],...
    'heatmaprange', [-4 4], 'showX', [], 'optolength', 50, 'usemedian', false,...
    'keepc', {'mouseid', 5; 'order', [1:10]}, 'outputdata', true, 'outputfs', 50, 'datatype', 'trig'};
out = viewoptostruct(datastruct_MPOAdLightNaive, varargin_viewopto);

%% Make satiated data struct
% Experimental group
[datastruct_MPOAdLightSatiated, n_series_MPOAdLightSatiated] =...
    mkoptostruct(inputloadingcell_MPOAdLightSatiated, 'defaultpath', defaultpath,...
    'externalsigma', [], 'zero_baseline', true, 'zero_baseline_per_session', true,...
    'linearleveling', false, 'useunfiltered', true, 'refilter', Hd, 'checkoptopulses', false,...
    'useinternalsigma', true);

%% View data struct satiated
% 

varargin_viewopto = {'datasets', [1 3], 'flip_signal', false, 'yrange', [],...
    'heatmaprange', [-4 4], 'showX', [], 'optolength', 50, 'usemedian', false,...
    'keepc', {'order', []}, 'outputdata', true, 'outputfs', 50, 'datatype', 'trig'};
out = viewoptostruct(datastruct_MPOAdLightSatiated, varargin_viewopto);

%% Make sham satiated data struct
% Experimental group
[datastruct_MPOAdLightShamSatiated, n_series_MPOAdLightShamSatiated] =...
    mkoptostruct(inputloadingcell_MPOAdLightShamSatiated, 'defaultpath', defaultpath,...
    'externalsigma', [], 'zero_baseline', true, 'zero_baseline_per_session', true,...
    'linearleveling', false, 'useunfiltered', true, 'refilter', Hd, 'checkoptopulses', false,...
    'useinternalsigma', true);

%% View data struct satiated
% 

varargin_viewopto = {'datasets', [1,3], 'flip_signal', false, 'yrange', [],...
    'heatmaprange', [-4 4], 'showX', [], 'optolength', 50, 'usemedian', false,...
    'keepc', {'order', [3:16]}, 'outputdata', true, 'outputfs', 50, 'datatype', 'trig'};
out = viewoptostruct(datastruct_MPOAdLightShamSatiated, varargin_viewopto);